language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: turfu-web
  api_key:
    secure: YMKQ/EWda5dzvR3NmtNmOIAIbLj1CNdotyJHpfKc3LShvjP3kXKLz0NIh82SQsypb/MJG50hIthoJs+lsV3VpvDHvBznflitClzu+uDBjtXIfPKX6Oxu7nWnGG/F6eqJIVELiTcsHEF58pnfsiyeziGHWkXMaCj5tgkVrFcFgRcgKN112jI5gwiKAPoP7UDiTgFwhYgzUvSmuze2630bhPEJDMc3ZySZjllRbs4w2MVbtqksAbFuZdOZ8XSD8ytHuoXRq25S5TfeU0El/1XJdzDbuoTmNf++bp4awMwW2Bmpb1EGkkYPVBSqKuYWIHK1MaOJ1O/SOQD037r5E3HVnCELtLE4RQYKQvNpODyYOU6hAuiYjBGG1sP56qXDaO2tk9ZH70UBRZIgfF1tGYgi44VlNipkhJ6ZyzvPQYd7NCIRTzAUxva2+5P2vJq4J78rLvNhJlDVSJ8hGLgageMPQ/0Gy4HqAyE2a0H/7CukvoJhGb+8zA511IdNMITFITo7HW+jD0FepQS8WT1F9045M1L9R7Q/7ETNwPCaeDWms+R/dF2+Isv0EucYiy/X2EexhLLT7VuNN9ywEd5hte/Uwc9WtCXOL5NJOmLZ74yiVuqSGilFalw/VADtFcnGG7RYWEjuaOzTn+3Yb99IUD9IUyJks+As4g13dwV5FamCtCI=
